config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :apps do 
    resources :plats
    collection do
      get :archived
    end
  end

  resources :users do
    member do 
      get :useage
      put :api_token, to: "users#refresh_api_token"
    end
  end

  resources :plats do
    resources :pkgs
    member do
      get :latest
    end
  end

  resources :pkgs, only:[:show] do
    member do
      get :manifest
    end
  end

  resources :udid, only:[:create,:index] do
    collection do
      get "mobileconfig"
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  
  resource :api, only:[] do
    post "pkgs" => "pkgs#api_create"
    put "plat/sort" => "plats#api_sort"
    get "plats/:plat_id/latest" => "plats#api_latest"
    get "plats/:plat_id/latest/download" => "plats#api_latest_download"
    get "pkgs/:pkg_id" => "pkgs#api_show"
  end
  
  root "apps#index"

end

app/models/pkg.rb
# == Schema Information
#
# Table name: pkgs
#
#  id             :integer          not null, primary key
#  app_id         :integer
#  name           :string
#  icon           :string
#  plat_name      :string
#  bundle_id      :string
#  version        :string
#  build          :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  plat_id        :integer
#  file           :string
#  size           :integer          default(0)
#  uniq_key       :string
#  user_id        :integer
#  deleted_at     :datetime
#  file_nick_name :string
#

class Pkg < ApplicationRecord

  serialize :ext_info, Hash

  attr_accessor :app_icon
  include PlatAble

  belongs_to :app
  belongs_to :plat
  belongs_to :user

  validates_presence_of :user_id
  validates_presence_of :file, :file_nick_name

  mount_uploader :icon, IconUploader
  mount_uploader :file, PkgUploader

  enum plat_name: {
    ios: 'ios',
    android: 'android'
  }

  after_create :save_icon
  after_create :clean_tmp

  def initialize pars
    super pars
    parsing
  end

  def uniq?
    !self.class.where({plat_id:plat_id,self.uniq_key.to_sym => self[self.uniq_key.to_sym]}).exists?
  end

  def size_mb
   '%.1f' % (size / (1024*1024.0))
  end

  def parsing
    if file.path
      parser.parse
      self.name = parser.app_name
      self.app_icon = parser.app_icon
      self.version = parser.app_version
      self.build = parser.app_build
      self.size = parser.app_size
      self.bundle_id = parser.app_bundle_id
      self.plat_name = parser.plat
      self.uniq_key = parser.app_uniq_key
      self.ext_info = parser.ext_info
    end
  end

  def parser
    @parser ||= PkgAdapter.pkg_adapter(file.path)
  end

  def save_icon
    if app_icon&.end_with?(".png")
      self.icon.store!(File.new(app_icon))
      self.save
    end
  end

  def clean_tmp
    if File.exist?(parser.tmp_dir)
      FileUtils.rm_rf parser.tmp_dir
    end
  end

  def pkg_after_store
    begin
      shell = "#{Rails.root.join("config")}/pkg_after_create.sh"
      if File.exist?(shell)
        system("bash #{shell} '#{file.path}'")
      end
    rescue => e
      puts e
    end
  end

  def install_url
    if ios?
      "itms-services://?action=download-manifest&url=#{Current.request.base_url}#{Rails.application.routes.url_helpers.manifest_pkg_path(self)}.plist"    
    else
      download_url
    end
  end

  def download_url
    file_path = "#{self.file}"
    if Settings.pkg_cdn_host.present? && !File.exist?("#{Rails.root.join('public')}#{file_path}")
      return "#{Settings.pkg_cdn_host}#{file_path}"
    else
      return "#{Current.request.base_url}#{file_path}"
    end
  end

  def display_file_name
    File.basename(file.path,".*")
  end

  def to_render_json
    key_white_list = [:id,:app_id,:name,:file_nick_name,:features,:plat_name,:plat_id,:bundle_id,:version,:build,:size_mb,:uniq_key,:user_id,:ext_info,:install_url,:download_url,:created_at]
    json = {}
    key_white_list.each do |key|
      json[key] = self.send(key.to_s)
    end
    json[:icon_url] = "#{Current.request.base_url}#{icon.url}"
    json
  end

  
end

app/controllers/pkgs_controller.rb
class PkgsController < ApplicationController
  protect_from_forgery :except => [:api_create]

  before_action :set_plat, only: [:new,:create]


  def show
    @pkg = Pkg.find params[:id]
    history = Pkg.where("id < ?",@pkg.id).limit(20).where(plat_id:@pkg.plat_id).id_desc
    history.each do |e|
      @history ||= {}
      time_str = e.created_at.strftime("%Y-%m-%d")
      @history[time_str] ||= []
      @history[time_str] << e
    end
    unless (browser.platform.ios? && !@pkg.ios?) || (browser.platform.android? && !@pkg.android?)
      @download_url = (browser.platform.android? || browser.platform.ios?) ? @pkg.install_url : @pkg.download_url
    end
  end

  #ios install manifest file
  def manifest
    @pkg = Pkg.find params[:id]
    stream = render_to_string(:template=>"pkgs/manifest.xml" )  
    render xml: stream
  end

  def new
    @pkg = @plat.pkgs.build
  end

  def create
    authorize!(:create, Pkg)
    pkg = Pkg.new(pkg_params.merge(user_id:current_user.id))
    pkg.app_id = pkg.plat.app_id

    unless pkg_params[:file_nick_name].present?
      pkg.file_nick_name = pkg.display_file_name
    end

    @plat.validate_pkg(pkg)
    
    pkg.save
    redirect_to pkg_path(pkg)
  rescue => e
    redirect_to new_plat_pkg_path(@plat), :flash => { :error => e.message }
  end

  def destroy
    pkg = Pkg.find params[:id]
    authorize!(:destroy, pkg)
    pkg.destroy!
    redirect_to app_plat_path(pkg.app, pkg.plat)
  end


  #api 提交包
  #params
  # - api_token: 授权 token  
  # - plat_id: 要传到的渠道
  # - pkg: 文件
  def api_create
    
    api_token = params[:token]

    user = User.find_by(api_token: api_token)
    unless user
      raise "401 Unauthorized"
    end

    plat = Plat.find params[:plat_id]

    pkg = Pkg.new({file:params[:file], user_id:user.id, plat_id:plat.id, file_nick_name:params[:file_nick_name],features:params[:features]})
    pkg.app_id = pkg.plat.app_id

    unless params[:file_nick_name].present?
      pkg.file_nick_name = pkg.display_file_name
    end

    plat.validate_pkg(pkg)
    
    pkg.save!

    render json: pkg.to_json

  rescue => e
    render json: {error: "#{e.message}"}
  end


  def api_show
    pkg_id = params[:pkg_id]
    pkg = Pkg.find(pkg_id)
    render :json => pkg.to_render_json
  rescue => e
    render json: {error: "#{e.message}"}
  end


  private
  
  def set_plat
    @plat = Plat.find(params[:plat_id])
  end

  # # Never trust parameters from the scary internet, only allow the white list through.
  def pkg_params
    params.require(:pkg).permit(:file,:plat_id,:file_nick_name,:features)
  end
end

app/views/pkgs/manifest.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>items</key>
  <array>
    <dict>
      <key>assets</key>
      <array>
        <dict>
          <key>kind</key>
          <string>software-package</string>
          <key>url</key>
          <string><%="#{@pkg.download_url}"%></string>
        </dict>
        <dict>
          <key>kind</key>
          <string>display-image</string>
          <key>url</key>
          <string><%="#{request.base_url}#{@pkg.icon}"%></string>
        </dict>
        <dict>
          <key>kind</key>
          <string>full-size-image</string>
          <key>url</key>
          <string><%="#{request.base_url}#{@pkg.icon}"%></string>
        </dict>
      </array>
      <key>metadata</key>
      <dict>
        <key>bundle-identifier</key>
        <string><%=@pkg.bundle_id%></string>
        <key>bundle-version</key>
        <string><%=@pkg.version%></string>
        <key>kind</key>
        <string>software</string>
        <key>title</key>
        <string><%=@pkg.name%></string>
      </dict>
    </dict>
  </array>
</dict>
</plist>

app/views/pkgs/new.html.erb
<%=render 'layouts/header'%>
<div class="container pkgs new">
  
  <%=render 'comoms/alert'%>

  <%=form_for @pkg, url:plat_pkgs_path(@plat), :html => { class: "app_form" } do |f|%>
    
    <%= hidden_field_tag "pkg[plat_id]", params[:plat_id] %>
    <div class="title"><span>提交包</span></div>
    <div class="form-group">
      <%= f.file_field :file, required:true, accept:".#{@plat.plat_ext_name}" %>
    </div>

    <div class="form-group">
      <label for="file_nick_name">重命名</label>
      <%= f.text_field :file_nick_name, class:"form-control", placeholder:"不填会直接使用文件名" %>
    </div>

    <div class="form-group">
      <label for="features">变更描述 <span class="ui-red-color">*</span></label>
      <%= f.text_area :features, required:true, class:"form-control", placeholder:"描述该包修改细节" %>
    </div>
    
    <%=f.submit "上传", class:"btn btn-primary ui-plat"%>
  <%end%>
</div>

app/views/pkgs/show.html.erb
<%=render 'layouts/header'%>

<div class="pkg show">

  <div class="wx-mask">
    <%=image_tag("weixin_mask.png")%>
  </div>

  <ul class="breadcrumb container">
    <li>
      <%=link_to @pkg.app.name, app_path(@pkg.app)%>
    </li>
    <li>
      <%=link_to @pkg.plat.name, app_plat_path(@pkg.app,@pkg.plat)%>
    </li>
    <li class="active"><%=@pkg.name%></li>
  </ul>

  <div class="first-page">
    <div class="info-container">
      <div class="app-info">
        <div class="icon">
          <%=image_tag(@pkg.icon.url)%>
        </div>
        <div class="title"><%=@pkg.name%></div>
        <div class="info">
          <%="版本:#{@pkg.version}, build:#{@pkg.build}"%>, <%=@pkg.size_mb%>MB 
          <br>
          <%=@pkg.created_at&.strftime("%Y-%m-%d %R") %> 
        </div>
      </div>

      <% if @download_url.present? %>
        <a class="download-btn" href="<%=@download_url%>">
          下载
        </a>
      <% else %>
        <a class="download-btn">
          无法下载
        </a>
      <% end %>

    </div>
  </div>

  <div class="qrcode">
    <div id="qrcode"></div>
    <label>或者用手机扫描上面的二维码安装</label>
  </div>


  <% if @pkg.features.present? %>
    <div class="features">
      <div class="wrap">
        <h3 class="title">变更描述:</h3>
        <p class="info">
          <%@pkg.features.split("\n").each do |line|%>
            <%=line%><br/>
          <%end%>
        </p>
      </div>
    </div>
  <% end %>

  <% @ext_info = @pkg.ext_info %>
  <% if @ext_info.present? %>
    <div class="extend-info">
      <div class="wrap">
        <div class="open-icon">
          <span>扩展信息:</span>
          <a class="glyphicon glyphicon-chevron-down"></a>
        </div>
        <p class="info" style="display: none;">
         <% if @ext_info.is_a?(Hash) %>
           <% @ext_info.each do |tilte,lines| %>
             <%=tilte%>:
             <% if lines.is_a?(Array) %>
               <%lines.each do |line| %>
                <br>
                &nbsp;&nbsp;&nbsp;-&nbsp;<%=line%>
               <% end %>
             <% else %>
                &nbsp;<%=lines%>
             <% end %>
             <br>
           <% end %>
         <% else %>
          <%=@ext_info%>
         <% end %>
        </p>  
      </div>
    </div>
  <% end %>
  

  <% if @history.present? %>
    <div class="history">
      <div class="wrap">
        <h3 class="title">历史版本</h3>
        <div class="day-block">
          <% @history.each do |key,value| %>
            <label class="title">
               <%=key%>
            </label>
            <ul>
              <%value.each do |v|%>
                <li>
                  <a href="<%=pkg_path(v)%>">
                    <%="#{v.version}(#{v.build})"%>&nbsp;&nbsp;<%="#{v.size_mb}MB"%>&nbsp;&nbsp;<%="#{v.created_at.strftime('%R')}"%>
                  </a>
                </li>
              <%end%>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  
  <footer class="footer">
    <a href="https://github.com/pluosi">- pluosi.com -</a>
  </footer>
</div>

<script type="text/javascript">

  var isWeixin = function () { //判断是否是微信
    var ua = navigator.userAgent.toLowerCase();
    return ua.match(/MicroMessenger/i) == "micromessenger";
  };

  $(function(){
    $('#qrcode').empty();
    new QRCode(document.getElementById("qrcode"), "<%=pkg_url(@pkg)%>");
    $(".open-icon").click(function(event) {
      $(".extend-info>.wrap>.info").slideToggle('fast')
    });

    if (isWeixin()) {
      $(".download-btn").click(function() {
        $(".wx-mask").show();
        return false;
      })
    }

  });

</script>