config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :apps do 
    resources :plats
    collection do
      get :archived
    end
  end

  resources :users do
    member do 
      get :useage
      put :api_token, to: "users#refresh_api_token"
    end
  end

  resources :plats do
    resources :pkgs
    member do
      get :latest
    end
  end

  resources :pkgs, only:[:show] do
    member do
      get :manifest
    end
  end

  resources :udid, only:[:create,:index] do
    collection do
      get "mobileconfig"
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  
  resource :api, only:[] do
    post "pkgs" => "pkgs#api_create"
    put "plat/sort" => "plats#api_sort"
    get "plats/:plat_id/latest" => "plats#api_latest"
    get "plats/:plat_id/latest/download" => "plats#api_latest_download"
    get "pkgs/:pkg_id" => "pkgs#api_show"
  end
  
  root "apps#index"

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-static-top app-host-nav theme-gray" id="top">
  <div class="container">
    <div class="navbar-header">
      <!-- <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#app-navbar" aria-controls="app-navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button> -->
      <a href="/" class="navbar-brand">APP HOST</a>
    </div>
    <nav id="app-navbar" class="navbar-collapse visible-md visible-lg">
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><a href="#">UDID</a></li> -->
        <% if signed_in? %>
          <li>
            <a data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false" href="<%=user_path(current_user)%>"><%=current_user.email%></a>
            <ul class="dropdown-menu">

              <% if can? :create, User %>
                <li>
                  <%=link_to '添加用户', new_user_path %>
                </li>
              <% end %>

              <li>
                <%=link_to '修改密码', edit_user_path(current_user) %>
              </li>
              <li>
                <%=link_to '使用文档', useage_user_path(current_user) %>
              </li>

              <% if current_user.admin? %>
                <li>
                  <%=link_to '用户管理', users_path %>
                </li>  
              <% end %>

              <li>
                <%=link_to '登出', session_path(current_user), form_class: "delete_btn", data: {:confirm => 'Are you sure?'}, :method => :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><a href="<%=new_session_path%>">管理</a></li>
        <% end %>
      </ul>
    </nav>



  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppHost</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  </head>

  <body>

    <%= yield %>
  </body>
</html>